//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 08:06:26 PM GMT 
//


package https.www_owasp_org.index_php.owasp_dependency_check;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_owasp_org.index_php.owasp_dependency_check package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_owasp_org.index_php.owasp_dependency_check
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.RelatedDependencies.RelatedDependency }
     * 
     */
    public Analysis.Dependencies.Dependency.RelatedDependencies.RelatedDependency createAnalysisDependenciesDependencyRelatedDependenciesRelatedDependency() {
        return new Analysis.Dependencies.Dependency.RelatedDependencies.RelatedDependency();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.VulnerableSoftware }
     * 
     */
    public Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.VulnerableSoftware createAnalysisDependenciesDependencyVulnerabilitiesVulnerabilityVulnerableSoftware() {
        return new Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.VulnerableSoftware();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.AnalysisExceptions }
     * 
     */
    public Analysis.Dependencies.Dependency.AnalysisExceptions createAnalysisDependenciesDependencyAnalysisExceptions() {
        return new Analysis.Dependencies.Dependency.AnalysisExceptions();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.Identifiers.Identifier }
     * 
     */
    public Analysis.Dependencies.Dependency.Identifiers.Identifier createAnalysisDependenciesDependencyIdentifiersIdentifier() {
        return new Analysis.Dependencies.Dependency.Identifiers.Identifier();
    }

    /**
     * Create an instance of {@link Analysis }
     * 
     */
    public Analysis createAnalysis() {
        return new Analysis();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.Vulnerabilities }
     * 
     */
    public Analysis.Dependencies.Dependency.Vulnerabilities createAnalysisDependenciesDependencyVulnerabilities() {
        return new Analysis.Dependencies.Dependency.Vulnerabilities();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.AnalysisExceptions.Exception }
     * 
     */
    public Analysis.Dependencies.Dependency.AnalysisExceptions.Exception createAnalysisDependenciesDependencyAnalysisExceptionsException() {
        return new Analysis.Dependencies.Dependency.AnalysisExceptions.Exception();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency }
     * 
     */
    public Analysis.Dependencies.Dependency createAnalysisDependenciesDependency() {
        return new Analysis.Dependencies.Dependency();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.References.Reference }
     * 
     */
    public Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.References.Reference createAnalysisDependenciesDependencyVulnerabilitiesVulnerabilityReferencesReference() {
        return new Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.References.Reference();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.Identifiers }
     * 
     */
    public Analysis.Dependencies.Dependency.Identifiers createAnalysisDependenciesDependencyIdentifiers() {
        return new Analysis.Dependencies.Dependency.Identifiers();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies }
     * 
     */
    public Analysis.Dependencies createAnalysisDependencies() {
        return new Analysis.Dependencies();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability }
     * 
     */
    public Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability createAnalysisDependenciesDependencyVulnerabilitiesVulnerability() {
        return new Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.References }
     * 
     */
    public Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.References createAnalysisDependenciesDependencyVulnerabilitiesVulnerabilityReferences() {
        return new Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.References();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.VulnerableSoftware.Software }
     * 
     */
    public Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.VulnerableSoftware.Software createAnalysisDependenciesDependencyVulnerabilitiesVulnerabilityVulnerableSoftwareSoftware() {
        return new Analysis.Dependencies.Dependency.Vulnerabilities.Vulnerability.VulnerableSoftware.Software();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.EvidenceCollected }
     * 
     */
    public Analysis.Dependencies.Dependency.EvidenceCollected createAnalysisDependenciesDependencyEvidenceCollected() {
        return new Analysis.Dependencies.Dependency.EvidenceCollected();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.AnalysisExceptions.Exception.InnerException }
     * 
     */
    public Analysis.Dependencies.Dependency.AnalysisExceptions.Exception.InnerException createAnalysisDependenciesDependencyAnalysisExceptionsExceptionInnerException() {
        return new Analysis.Dependencies.Dependency.AnalysisExceptions.Exception.InnerException();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.AnalysisExceptions.Exception.StackTrace }
     * 
     */
    public Analysis.Dependencies.Dependency.AnalysisExceptions.Exception.StackTrace createAnalysisDependenciesDependencyAnalysisExceptionsExceptionStackTrace() {
        return new Analysis.Dependencies.Dependency.AnalysisExceptions.Exception.StackTrace();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.EvidenceCollected.Evidence }
     * 
     */
    public Analysis.Dependencies.Dependency.EvidenceCollected.Evidence createAnalysisDependenciesDependencyEvidenceCollectedEvidence() {
        return new Analysis.Dependencies.Dependency.EvidenceCollected.Evidence();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.AnalysisExceptions.Exception.InnerException.StackTrace }
     * 
     */
    public Analysis.Dependencies.Dependency.AnalysisExceptions.Exception.InnerException.StackTrace createAnalysisDependenciesDependencyAnalysisExceptionsExceptionInnerExceptionStackTrace() {
        return new Analysis.Dependencies.Dependency.AnalysisExceptions.Exception.InnerException.StackTrace();
    }

    /**
     * Create an instance of {@link Analysis.ProjectInfo }
     * 
     */
    public Analysis.ProjectInfo createAnalysisProjectInfo() {
        return new Analysis.ProjectInfo();
    }

    /**
     * Create an instance of {@link Analysis.Dependencies.Dependency.RelatedDependencies }
     * 
     */
    public Analysis.Dependencies.Dependency.RelatedDependencies createAnalysisDependenciesDependencyRelatedDependencies() {
        return new Analysis.Dependencies.Dependency.RelatedDependencies();
    }

}
