//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 08:06:26 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.owasp.org/index.php/OWASP_Dependency_Check", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_owasp_org.index_php.owasp_dependency_check;
